node('uislave') {
    properties([
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')),
        [$class: 'HudsonNotificationProperty', endpoints: [[buildNotes: '', retries: 3, urlInfo: [urlOrId: 'https://conduit.ethos.corp.adobe.com/v1/jenkins/status', urlType: 'PUBLIC']]]]
    ])

    // define the secrets and the env variables
    def secrets = [
        [$class: 'VaultSecret', path: 'secret/ethos/tenants/mobile_services/nova/shared/users/generic/novaprj/artifactory/corp/apikey', secretValues: [
            [$class: 'VaultSecretValue', envVar: 'ARTIFACTORY_API_TOKEN', vaultKey: 'value']]]
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [$class: 'VaultConfiguration',
                      vaultUrl: 'https://vault.loc.adobe.net',
                      vaultCredentialId: 'nova-vault-token-credential']

    // inside this block your credentials will be available as env variables
    wrap([$class: 'VaultBuildWrapper', configuration: configuration, vaultSecrets: secrets]) {
        stage('verify') {
            cleanWs()
            checkout scm
            sh '''#!/bin/bash
                echo running
                export ARTIFACTORY_USER=novaprj
                make ci
            '''
            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'coverage/lcov-report/', reportFiles: 'index.html', reportName: 'Griffon Plugin Bridge HTML Report', reportTitles: ''])
        }
    }
}