version: 2
jobs:
  build:
    working_directory: ~/airglow-build
    docker:
      - image: circleci/node:10.15.3
    steps: # a collection of executable commands
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: eslint
          command: npm run lint -- --format junit -o reports/junit/js-lint-results.xml
      - run: mkdir ~/junit
      - run:
          command: karma start ./karma.conf.js
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
          when: always 
      - store_test_results:
          path: ./junit
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ./junit
      - run:
          name: Upload Code Coverage Report
          command: npx codecov