version: 2
jobs:
  build:
    working_directory: ~/airglow-build
    docker:
      - image: circleci/node:10.15.3
    steps: # a collection of executable commands
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm ci
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lerna bootstrap
          command: npx lerna bootstrap
      - run:
          name: build
          command: npm run build
      - run:
          name: eslint
          command: npm run lint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Run tests with JUnit as reporter
          command: npm run coverage -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: reports/junit
      - run:
          name: Upload Code Coverage Report
          command: npx codecov