node('uislave') {
    properties([
        buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10')),
        pipelineTriggers([pollSCM('H/5 * * * *')]),
        [$class: 'HudsonNotificationProperty', endpoints: [[buildNotes: '', retries: 3, urlInfo: [urlOrId: 'https://conduit.ethos.corp.adobe.com/v1/jenkins/status', urlType: 'PUBLIC']]]]
    ])

    // define the secrets and the env variables
    def secrets = [
        [$class: 'VaultSecret', path: 'secret/ethos/tenants/mobile_services/nova/shared/users/generic/novaprj/artifactory/corp/apikey', secretValues: [
            [$class: 'VaultSecretValue', envVar: 'ARTIFACTORY_API_TOKEN', vaultKey: 'value']]],
        [$class: 'VaultSecret', path: 'secret/ethos/tenants/mobile_services/nova/shared/users/generic/novaprj/ssh/pass', secretValues: [
            [$class: 'VaultSecretValue', envVar: 'SSH_KEY_PASSWORD', vaultKey: 'value']]],
        [$class: 'VaultSecret', path: 'secret/ethos/tenants/mobile_services/nova/shared/users/generic/novaprj/ssh/private', secretValues: [
            [$class: 'VaultSecretValue', envVar: 'SSH_PRIVATE_KEY_CONTENTS', vaultKey: 'value']]]
    ]

    // optional configuration, if you do not provide this the next higher configuration
    // (e.g. folder or global) will be used
    def configuration = [$class: 'VaultConfiguration',
                      vaultUrl: 'https://vault.loc.adobe.net',
                      vaultCredentialId: 'nova-vault-token-credential']

    // inside this block your credentials will be available as env variables
    wrap([$class: 'VaultBuildWrapper', configuration: configuration, vaultSecrets: secrets]) {
        stage('publish') {
            cleanWs()
            git branch: 'master', changelog: false, credentialsId: 'novaprj-git-ssh-key', url: 'git@git.corp.adobe.com:dms-mobile/griffon-plugin-bridge.git'
            sh '''#!/bin/bash
                echo running
                export ARTIFACTORY_USER=novaprj
                make deploy
            '''
        }
        stage('notify') {
            emailext (
                to: 'grossen@adobe.com, athomson@adobe.com, phuo@adobe.com, long@adobe.com',
                subject: '$DEFAULT_SUBJECT',
                body: '''
                '${DEFAULT_CONTENT}'\n\nThe following packages have been published to artifactory\n\n'${FILE, path=".released-packages"}'
                '''
            )
        }
    }
}